language: node_js
# before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
node_js:
  - 9
  - 8
  - 7
  - node

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: npm run test:coverage && cat ./_coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./_coverage