language: node_js
node_js:
  - 9
  - 8
  - 7
  - 6
  - 5
  - 4
  - 3
  - node

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: npm run test:coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage